# Generated by Django 3.1.3 on 2020-11-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201129_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleorder', verbose_name='Orden de Venta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Producto')),
            ],
        ),
    ]
